---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: reference-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: reference-operator
  name: reference-operator-leader-election-rolebinding
  namespace: reference-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reference-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: reference-operator-controller-manager
    namespace: reference-operator-system
